Selenium webdriver
emmaaghlamazyan94/Epam pull request #4
Opened 2021-03-20 09:27 UTC by emmaaghlamazyan94

2021-03-20 11:29 UTC, David91 requested changes

2021-03-20 11:29 UTC, David91 commented on pom.xml
> +        </dependency>
There are 2 testng dependencies. Remove one of them

2021-03-20 11:29 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        Assert.assertEquals(actualVersion, expectedVersion, "Check version");
1. Move the assertion where your actual result is known, so the assertion will be in the right place.
2. Write more meaningful assertion messages ( not like "Check version" )

2021-03-20 11:29 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        WebElement element1 = driver.findElement(By.name("search"));
Give elements meaningful names, so reviewer can understand what kind of webelement you've found.

2021-03-20 11:29 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +
Correct error message.

2021-03-20 11:39 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        WebElement lastVersion = driver.findElement(By.linkText("3.141.59"));
Selector seems to be not correct ( although it works ), because there can be a link, which has the text "3.141.59", but doesn't show the latest stable version, but something else. So You should find the link, which shows the latest stable version.

2021-03-20 22:26 UTC, David91 requested changes

2021-03-20 22:26 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        String actualname = driver.findElement(By.linkText("Selenium WebDriver")).getText().toLowerCase();
Selector looks not bad, but can be error prone, as strongly depends on writing style of link text. So if tomorrow link text will change to 'Selenium Webdriver', test will fail.
Try another approach.

2021-03-20 22:26 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +                (By.xpath("//p/a[contains(@href,'https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar')]"));
This xpath selector works for now, but it strongly depends on the link formation, that has @href attribute. It doesn't matter under which link can be .jar file, we just want to see if the stable version is '3.141.59'. So try to find out how to select the exact latest stable version link, not a link which downloads standalone .jar file and accidently matches with latest stable version link.

2021-03-20 22:26 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        Assert.assertEquals(actualname, expectedName, "Selenium Webdriver Not Found");
Write more meaningful error message, which will show the exact problem.

2021-03-21 19:24 UTC, David91 requested changes

2021-03-21 19:24 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +                (By.xpath("//p[text()='Latest stable version ']//a[text()='3.141.59']"));
Part of selector is redundant, will discuss later.

2021-03-21 19:24 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +                (By.xpath("//*[contains(text(),'Selenium WebDriver')]")).getText().toLowerCase();
This is wrong selector, because you find anything that have text "Selenium WebDriver" in it. It doesn't matter text appears in search result links or not, but it should, therefore you should change the selector. Also make your selector independent from the writing style of "selenium webdriver" text in link. So your selector ( or your code ) should work regardless if it is written "Selenium WebDriver" or 'seLenium weBDriver" in link text.

2021-03-22 10:36 UTC, David91 requested changes

2021-03-22 10:36 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +        searchBox.sendKeys(expectedName + Keys.ENTER);
Your code should wait some time till result will appear.

2021-03-22 10:36 UTC, David91 commented on src/test/java/Documents/OpenBrowserTest.java
> +                (By.xpath("//div[@class='gs-title']//a")).getText().toLowerCase();
The selector is incorrect, you can't guess where link containing "selenium webdriver" appears. At first or in for example 4th link. So you should change the logic.

2021-03-22 16:58 UTC, chandranik90 commented
Move the driver file into `resources` folder

2021-03-22 16:58 UTC, chandranik90 requested changes

2021-03-22 16:58 UTC, chandranik90 commented on src/test/java/Documents/OpenBrowserTest.java
> +package Documents;
Package name should not contain upper-cases based on the naming convention

2021-03-22 20:52 UTC, David91 requested changes

2021-03-22 20:52 UTC, David91 commented on src/test/java/OpenBrowserTest.java
> +        List<WebElement> links = driver.findElements(By.xpath("//div[@class = 'gs-title']//a"));
This selector needs a small change, as it selects one more link except search result link.

2021-03-22 21:11 UTC, David91 requested changes

2021-03-22 21:11 UTC, David91 commented on src/test/java/OpenBrowserTest.java
> +        Assert.assertEquals(actualVersion, expectedVersion, "Incorrect Selenium Server Version Number");
Fix the error message. It should be about latest stable version, not selenium server version number.

2021-03-22 21:11 UTC, David91 commented on src/test/java/OpenBrowserTest.java
> +            Assert.assertTrue(checkCondition, "No results found for " + expectedName);
Assertion is written in wrong place. If test passes, it's just because most probably at the first iteration condition is true, so loop breaks. If at first iteration your condition fails, then your test will fail with Assertion.

2021-03-22 21:21 UTC, David91 approved these changes

2021-03-22 21:24 UTC, merged