Test greetz.nl
emmaaghlamazyan94/Epam pull request #5
Opened 2021-03-24 10:47 UTC by emmaaghlamazyan94

2021-03-24 16:03 UTC, chandranik90 requested changes

2021-03-24 16:03 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        Double priceMultiply = 4 * price;
I have noticed that the initial price changes when the item count is being increased. It means, that a potential discount can be applied to the item. Hence, the final calculated amount will be changed as well. So, for having valid test, please gather the normal price after changing the amount.

2021-03-24 16:23 UTC, emmaaghlamazyan94 commented on src/test/java/GreetzTest.java
> +    @BeforeMethod
It was just the task 1, only added BeforeMethod, but I will combine both with corrections

2021-03-25 18:15 UTC, chandranik90 approved these changes

2021-03-25 18:15 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +    String email = "register@gmail.com";
Always use access modifiers. And always use private, if there is no special reason for not doing so

2021-03-25 18:15 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +    @Test(priority = -1)
Not sure, if negative priority is acceptable :) At least I never face it. It's better to start from 0

2021-03-25 19:55 UTC, merged