Add amazon.com test
emmaaghlamazyan94/Epam pull request #7
Opened 2021-03-31 15:59 UTC by emmaaghlamazyan94

2021-04-01 18:29 UTC, chandranik90 requested changes

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        for (WebElement authorLink : authors) {
What's the reason of finding list of items, click on the first and break the loop?

2021-04-01 18:29 UTC, chandranik90 commented on src/test/java/AmazonTest.java
> +        authorPage.clickOnSearchResult();
Seems, this is not an `AuthorPage` yet. Logically, you are still on `Books Page` when clicking on found result. Only after that you navigate to `Author Page`. So, the `clickOnSearchResult` method should be moved to `Books Page`

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        WebElement lowToHigh = driver.findElement(By.id("dropdown1_1"));
Bad locator. Use text to find the option in dropdown

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        lowToHigh.click();
This action brings to page reload. So, it's necessary to wait for page to load

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        ArrayList<Float> priceList = new ArrayList();
Use `<>` operator when initializing generic class

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        for (int i = 0; i < prices.size(); i = i++) {
is the `i = i++` really what you want to achieve? if yes, could you please explain?

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        List<WebElement> prices = driver.findElements(By.xpath("//span[@class='a-price']//span[@aria-hidden='true']"));
This locator doesn't find anything for me. Please recheck it

2021-04-01 18:29 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        if (isListSorted(priceList)) {
Simply replace by `return isListSorted(priceList)`

2021-04-01 20:33 UTC, emmaaghlamazyan94 commented on src/main/java/pages/AuthorPage.java
> +        for (int i = 0; i < prices.size(); i = i++) {
No, it was just misprint

2021-04-02 12:52 UTC, emmaaghlamazyan94 commented on src/main/java/pages/AuthorPage.java
> +        for (WebElement authorLink : authors) {
Not all results are hyperlinks, some are only the name of the author, so I find the first clickable element, click on it and break.

2021-04-02 13:44 UTC, emmaaghlamazyan94 commented on src/main/java/pages/BooksPage.java
> +        wait.until(ExpectedConditions.numberOfElementsToBeMoreThan
Is it good to block wait with try catch? And if there is no books found, catch the exception?

2021-04-04 18:55 UTC, chandranik90 approved these changes

2021-04-04 18:55 UTC, chandranik90 commented on src/test/java/AmazonTest.java
> +        String textToSearch = ("Books by " + authorFullName).toLowerCase();
Still the same. This is your text. And you could just write it in lowercase initially

2021-04-04 20:39 UTC, merged