Add PageFactory to amazon.com test
emmaaghlamazyan94/Epam pull request #8
Opened 2021-04-05 08:57 UTC by emmaaghlamazyan94

2021-04-05 14:09 UTC, David91 requested changes

2021-04-05 14:09 UTC, David91 commented on src/main/java/pages/BooksPage.java
> +                    ((By) books, 0));
`(By) books` conversion is impossible, as these types are incompatible. Your code always throws an exception at runtime and it's also unclear why you handle the exception when it's mindless to continue execution if a page isn't loaded.
Why you don't receive an error message compile-time? The reason perhaps is hidden in a fact, that `books` is a WebElement actually, which is an interface and the compiler isn't able to detect the actual object type on which books variable refers to. It is always known at runtime.
So remove this cast and don't handle the exception thrown by the explicit wait, as it's mindless to continue if the page isn't loaded.

2021-04-05 14:09 UTC, David91 commented on src/main/java/pages/AuthorPage.java
> +
What's the meaning of this method? Not counting that method returning `List<WebElement>` shouldn't be public, as it's against Page Object principles.

2021-04-05 16:21 UTC, emmaaghlamazyan94 commented on src/main/java/pages/AuthorPage.java
> +
![Capture](https://user-images.githubusercontent.com/80035348/113596968-0f1a6100-964c-11eb-9561-a76f27af2737.PNG)
I wanted to fix this comment

2021-04-05 16:22 UTC, emmaaghlamazyan94 commented on src/main/java/pages/AuthorPage.java
> +
Got List of authors from page, and wrote logic in Test class

2021-04-06 13:43 UTC, David91 commented on src/main/java/pages/BooksPage.java
> +    }
Remind me tomorrow to talk about this kind of method.

2021-04-06 13:44 UTC, David91 approved these changes

2021-04-06 18:29 UTC, merged